import type { Metadata } from "next"
import { Inter } from "next/font/google"
import "../style/globals.css"
import Navbar from "@/components/navbar/navbar"
import { Toaster } from "@/components/ui/sonner"
import { RefProvider } from "@/provider/provider"

const inter = Inter({ subsets: ["latin"] })

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <RefProvider>
          <Navbar />
          <Toaster />
          {children}
        </RefProvider>
      </body>
    </html>
  )
}
